### ISSUE TITLE
Missing zipcode 93703

### ISSUE THREAD

**Issue by TimothyDJewell** [cfpb/django-hud#24]
In the past, I've loaded the data via https://www.consumerfinance.gov/hud-api-replace/93703/ (or similar) as a way to access the JSON data, but it seems that this particular zipcode is no longer returning results.  Going to https://www.consumerfinance.gov/find-a-housing-counselor/?zipcode=93703, however, appeared to give me the expected counselors.  I looked into the page and found that it uses a different method to look up the counselors now (via cfpb/cfgov-refresh#3106?).  This made me wonder: is /hud-api-replace/ no longer working as expected?  Further, is there a better way for me to pull the data of the counselors from the site?

**Comment by chosak** [comment]
Hi @TimothyDJewell thanks for bringing this to our attention.

The lack of data for that zipcode was due to an internal problem with the data. I've refreshed things on our side and [you should see the correct data there now](https://www.consumerfinance.gov/hud-api-replace/93703/).

Longer term, you're correct that www.consumerfinance.gov is no longer using those API methods to serve housing counselor data on the site (implemented in [cfgov-refresh#3016](https://github.com/cfpb/cfgov-refresh/pull/3106), [#3017](https://github.com/cfpb/cfgov-refresh/pull/3107), and [#3186](https://github.com/cfpb/cfgov-refresh/pull/3186)). We're evaluating next steps and a long-term plan for how best to support these endpoints. It'd be helpful if you'd like to share anything about the needs of your particular use case.

**Comment by TimothyDJewell** [comment]
Hi @chosak, I work on an loan origination software that tracks the 10 closest homeowner counseling organizations to the borrower based on their address.  We use this API to populate the organizations.

**Comment by chosak** [comment]
@TimothyDJewell thanks for the feedback. As the data is now refreshed I'm going to close this issue but please let us know if you see any other omissions in future.
